name: ding_dong
description: "Um projeto de alarme agendado para escolas"

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  flutter_local_notifications: ^20.1.0
  intl: ^0.20.2
  go_router: ^17.1.0
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  hive_ce_flutter: ^2.3.4
  json_annotation: ^4.11.0
  freezed_annotation: ^3.1.0
  window_manager: ^0.5.1
  system_tray: ^2.0.3
  launch_at_startup: ^0.5.1
  package_info_plus: ^9.0.0
  pluto_grid: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  injectable_generator: ^2.12.0
  json_serializable: ^6.13.0
  freezed: ^3.2.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/sounds/
